<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7667555d-8d67-4fc2-8fd7-f897a1ddb89a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="4.2.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.14.0" />
  </ItemGroup>

</Project>
